In [2]:
import numpy as np

# 1. 
vect = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)
print(vect)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [3]:
#2. 
zero_matrix = np.zeros((3, 3))
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#3. 
rand_matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print(rand_matrix_5x5)

[[ 4  3 10  3  4]
 [ 8  9 10  2 10]
 [10  2  1  3 10]
 [10  1 10  3  7]
 [ 1  5  7  5  2]]


In [7]:
#4. 
random_matrix_4x4 = np.random.randint(0, 2, size=(4, 4))
print(random_matrix_4x4)

[[0 0 0 1]
 [1 0 0 0]
 [1 1 1 1]
 [1 0 1 1]]


In [8]:
# 5.  
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)


sum_array = a + b
diff_array = a - b
multipli_array = a * b

print(a)
print(b)
print(f"Sum: {sum_array}")
print(f"Difference: {diff_array}")
print(f"Multipli: {multipli_array}")

[ 1 10  9  9  8]
[7 6 4 7 3]
Sum: [ 8 16 13 16 11]
Difference: [-6  4  5  2  5]
Multipli: [ 7 60 36 63 24]


In [10]:
# 6.
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

scal_mlt = np.dot(vector1, vector2)

print(f"Vector 1: {vector1}")
print(f"Vector 2: {vector2}")
print(f"Scalar multiplication: {scal_mlt}")

Vector 1: [0.68469614 0.68092751 0.95155774 0.94073586 0.92450147 0.5803739
 0.07396633]
Vector 2: [0.1477599  0.05994076 0.20561601 0.72150361 0.27646399 0.58310517
 0.29191576]
Scalar multiplication: 1.631988100574588


In [11]:
#7. 
matrix_2x2 = np.random.randint(1, 11, (2, 2))
matrix_2x3 = np.random.randint(1, 11, (2, 3))

dot_matrix = np.dot(matrix_2x2, matrix_2x3)

print(f"2x2 Matrix:\n {matrix_2x2}")
print(f"2x3 Matrix:\n {matrix_2x3}")
print(f"Dot Matrix:\n {dot_matrix}")

2x2 Matrix:
 [[3 2]
 [5 9]]
2x3 Matrix:
 [[ 9 10  7]
 [ 7  9  7]]
Dot Matrix:
 [[ 41  48  35]
 [108 131  98]]


In [12]:
#8. 
matrix_3x3 = np.random.randint(1, 11, (3, 3))


inverse_matrix = np.linalg.inv(matrix_3x3)

print(f"3x3 Matrix:\n {matrix_3x3}")
print(f"Inverse Matrix:\n {inverse_matrix}")

3x3 Matrix:
 [[ 7  5  5]
 [ 7  5 10]
 [ 5  7  2]]
Inverse Matrix:
 [[ 0.5        -0.20833333 -0.20833333]
 [-0.3         0.09166667  0.29166667]
 [-0.2         0.2         0.        ]]


In [13]:
#9. 
matrix_4x4 = np.random.rand(4, 4)

transposed_matrix = matrix_4x4.T

print(f"4x4 Matrix:\n {matrix_4x4}")
print(f"Transposed Matrix:\n {transposed_matrix}")

4x4 Matrix:
 [[0.5885777  0.9862027  0.16952237 0.98799845]
 [0.76510769 0.51602134 0.10900346 0.55328418]
 [0.69022246 0.43072646 0.8991206  0.41100359]
 [0.62768929 0.38036537 0.13879339 0.41119384]]
Transposed Matrix:
 [[0.5885777  0.76510769 0.69022246 0.62768929]
 [0.9862027  0.51602134 0.43072646 0.38036537]
 [0.16952237 0.10900346 0.8991206  0.13879339]
 [0.98799845 0.55328418 0.41100359 0.41119384]]


In [14]:
#10. 
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector_4 = np.random.randint(1, 11, 4)

dot_vector = np.dot(matrix_3x4, vector_4)

print(f"3x4 Matrix:\n {matrix_3x4}")
print(f"4-element Vector: {vector_4}")
print(f"Dot Vector: {dot_vector}")

3x4 Matrix:
 [[ 5  5  1  3]
 [ 8  2  7  5]
 [10  2  3  7]]
4-element Vector: [ 2  4  7 10]
Dot Vector: [ 67 123 119]


In [15]:
#11. 
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)


dot_vector = np.dot(matrix_2x3, vector_3)

print(f"2x3 Matrix:\n {matrix_2x3}")
print(f"3-element Vector: {vector_3}")
print(f"Dot Vector: {dot_vector}")

2x3 Matrix:
 [[0.62107476 0.17765079 0.70463469]
 [0.08116574 0.26144183 0.48836725]]
3-element Vector: [0.73728058 0.05117868 0.26408537]
Dot Vector: [0.653082   0.20219282]


In [16]:
#12. 
matrix1_2x2 = np.random.randint(1, 11, (2, 2))
matrix2_2x2 = np.random.randint(1, 11, (2, 2))


elementwise = matrix1_2x2 * matrix2_2x2

print(f"Matrix 1:\n {matrix1_2x2}")
print(f"Matrix 2:\n {matrix2_2x2}")
print(f"Elementwise:\n {elementwise}")

Matrix 1:
 [[10  8]
 [ 1  8]]
Matrix 2:
 [[5 7]
 [4 7]]
Elementwise:
 [[50 56]
 [ 4 56]]


In [17]:
#13. 
matrix1_2x2 = np.random.randint(1, 11, (2, 2))
matrix2_2x2 = np.random.randint(1, 11, (2, 2))

dot_matrix = np.dot(matrix1_2x2, matrix2_2x2)

print(f"Matrix 1:\n {matrix1_2x2}")
print(f"Matrix 2:\n {matrix2_2x2}")
print(f"Dot Matrix:\n {dot_matrix}")

Matrix 1:
 [[9 4]
 [2 3]]
Matrix 2:
 [[8 3]
 [5 2]]
Dot Matrix:
 [[92 35]
 [31 12]]


In [18]:
#14. 
matrix_sum = np.sum(matrix_5x5)

print(f"5x5 Matrix:\n {matrix_5x5}")
print(f"Sum of elements: {matrix_sum}")

5x5 Matrix:
 [[15 22 56  3 88]
 [76 65 30 48 17]
 [34 99 75 98 38]
 [16 63 10 41 29]
 [76 98 59 47 78]]
Sum of elements: 1281


In [19]:
#15.
matrix1_4x4 = np.random.randint(1, 11, (4, 4))
matrix2_4x4 = np.random.randint(1, 11, (4, 4))


matrix_difference = matrix1_4x4 - matrix2_4x4

print(f"Matrix 1:\n {matrix1_4x4}")
print(f"Matrix 2:\n {matrix2_4x4}")
print(f"Matrix Difference:\n {matrix_difference}")

Matrix 1:
 [[ 4  5  4  9]
 [ 7  3  7  7]
 [ 7  7  8  7]
 [ 6  8  2 10]]
Matrix 2:
 [[ 1  4 10  2]
 [ 4  8  3  1]
 [ 9  1  1  9]
 [ 9 10 10  7]]
Matrix Difference:
 [[ 3  1 -6  7]
 [ 3 -5  4  6]
 [-2  6  7 -2]
 [-3 -2 -8  3]]


In [20]:
# 16.
matrix_3x3 = np.random.rand(3, 3)

row_sums = np.sum(matrix_3x3, axis=1).reshape(-1, 1)

print(f"3x3 Matrix:\n {matrix_3x3}")
print(f"Row sums:\n {row_sums}")

3x3 Matrix:
 [[0.25839395 0.23560292 0.52412128]
 [0.77033038 0.30867953 0.41807275]
 [0.14284927 0.7012538  0.21645337]]
Row sums:
 [[1.01811815]
 [1.49708267]
 [1.06055644]]


In [21]:
#17.
matrix_3x4 = np.random.randint(1, 11, (3, 4))

squared_matrix = np.square(matrix_3x4)

print(f"3x4 Matrix:\n {matrix_3x4}")
print(f"Squared Matrix:\n {squared_matrix}")

3x4 Matrix:
 [[ 6  7  2  2]
 [ 9  9 10  4]
 [10  8  6 10]]
Squared Matrix:
 [[ 36  49   4   4]
 [ 81  81 100  16]
 [100  64  36 100]]


In [22]:
#18.  
vector_4 = np.random.randint(1, 51, 4)


sqrt_vector = np.sqrt(vector_4)

print(f"Original Vector: {vector_4}")
print(f"Square Root Vector: {sqrt_vector}")

Original Vector: [ 7 30 38 25]
Square Root Vector: [2.64575131 5.47722558 6.164414   5.        ]
